### ISSUE TITLE
Compilation problems.

### ISSUE THREAD

**Issue by weekends** [esp32m/core#26]
Can't compiled with latest idf and yarn tools, problem with downloading of the ts-libs.

**Comment by dyarkovoy** [comment]
Can you provide the exact error message you are getting?

**Comment by weekends** [comment]
j -MF esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj -c /home/grigory/workspace/esp32/Weekend/core/examples/basic/main/main.cpp
/home/grigory/workspace/esp32/Weekend/core/examples/basic/main/main.cpp:17:10: fatal error: dist/ui.hpp: No such file or directory
   17 | #include <dist/ui.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
BUG: component_requirements.py: cannot match original component filename for source component main
ninja failed with exit code 1, output of the command is in the /home/grigory/workspace/esp32/Weekend/core/examples/basic/build/log/idf_py_stderr_output_1190537 and /home/grigory/workspace/esp32/Weekend/core/examples/basic/build/log/idf_py_stdout_output_1190537

**Comment by dyarkovoy** [comment]
This error is secondary, dist/ui.hpp is a generated file that could not be generated for some reason, so there should be another error message above. Can you look for it? I just tried to compile on my end and it goes without issues, so I need more information from you to diagnose the problem.

**Comment by weekends** [comment]
esp32m-ui:INFO:linking /home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui to /home/grigory/workspace/esp32/Weekend/core/examples/basic/managed_components/esp32m/web-ui
 YN0000:  Yarn 4.1.0
 YN0000:  Resolution step
 YN0001:  RequestError
    at ClientRequest.<anonymous> (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:147:14258)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:530:35)
    at u.emit (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:142:14420)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:90:21)AggregateError [ETIMEDOUT]:
    at internalConnectMultiple (node:net:1139:18)
    at internalConnectMultiple (node:net:1215:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1739:5)
    at listOnTimeout (node:internal/timers:596:11)
    at process.processTimers (node:internal/timers:529:7)
 YN0000:  Completed in 2m 31s
 YN0000:  Failed with errors in 2m 31s
esp32m-ui:INFO:building /home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui
Internal Error: ui@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Xx.getCandidates (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:205:8149)
    at Dd.getCandidates (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:141:1311)
    at /home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:210:8409
    at Ky (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:140:53916)
    at Fe (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:210:8389)
    at async Promise.allSettled (index 0)
    at async Uc (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:140:53244)
    at async /home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:210:9140
    at async Qi.startProgressPromise (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:140:137284)
    at async Pt.resolveEverything (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:210:7138)
[1146/1157]
[

**Comment by weekends** [comment]
One time i can compile, when remove yarn.lock, then example compiled. After that i'm enable olimex ethernet and try to rebuild - now not compiled again and removing of the yarn.lock can't help.

**Comment by dyarkovoy** [comment]
This looks like HTTP connection problem. Yarn cannot download the required node modules from the Internet, maybe your IP is rate limited, I've seen this a couple of times with yarn/npm repositories. Try running `yarn install` manually in ./build/web-ui and also check if you can open https://registry.yarnpkg.com in a browser. If not, try with a VPN

**Comment by weekends** [comment]
https://registry.yarnpkg.com/ - opened success in browser.

➤ YN0035: │ @ts-libs/dev@npm:*: Package not found
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@ts-libs%2fdev

**Comment by weekends** [comment]
Manual opening of the link return same error (404 Not Found)

**Comment by dyarkovoy** [comment]
Okay I see, @ts-libs/dev is locally-linked module, it is a part of the esp32m git repository. Please check ./build/web-ui/package.json, you will see `portal:...` links there at the bottom, please see if the paths point to existing locations, you have permissions to open the folders etc.

**Comment by weekends** [comment]
No "portal:..." inside:

{
    "name": "ui",
    "version": "1.0.0",
    "license": "MIT",
    "scripts": {
        "build": "NODE_OPTIONS='--preserve-symlinks' webpack --node-env=production",
        "compile": "NODE_OPTIONS='--preserve-symlinks' webpack --node-env=development",
        "analyze": "NODE_OPTIONS='--preserve-symlinks' webpack --node-env=production --env destination=analyze",
        "start": "NODE_OPTIONS='--preserve-symlinks' webpack serve --node-env=development"
    },
    "devDependencies": {
        "@ts-libs/dev": "*",
        "webpack": "*",
        "webpack-cli": "*",
        "webpack-dev-server": "*"
    },
    "dependencies": {
        "@esp32m/ui": "*",
        "@ts-libs/ui-app": "*",
        "lodash": "*",
        "react": "*"
    },
    "packageManager": "yarn@4.1.0",
    "resolutions": {
        "react": "*",
        "lodash": "*",
        "webpack": "*",
        "webpack-cli": "*",
        "webpack-dev-server": "*"
    }
}

**Comment by dyarkovoy** [comment]
If you open the root of the esp32m/core cloned repo, do you have ./esp32m/web-ui/ts-libs/ folder there, is it accessible, and does it contain a number of sub-folders with typescript files?

**Comment by weekends** [comment]
Yes, shure: ls -l esp32m/web-ui/ts-libs/
grigory@weekend esp32/Weekend/core $ ls -l esp32m/web-ui/ts-libs/
итого 44
drwxr-xr-x 4 grigory grigory 4096 мар 28 00:56 dev
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 log
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 plugins
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 redux
drwxr-xr-x 4 grigory grigory 4096 мар 28 00:56 tools
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 ui-app
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 ui-base
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 ui-forms
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 ui-i18n
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 ui-navbar
drwxr-xr-x 3 grigory grigory 4096 мар 28 00:56 ui-snack

**Comment by dyarkovoy** [comment]
Okay, then somehow the UI build script decided that it shouldn't include UI libraries with the build. If you open esp32m/scripts/build-ui.py, you will see a number of diagnostic messages it emits during build process. Can you check your console build log for these messages? Specifically, you should see `linking {self.dir} to {target}` messages that indicate the @ts/lib links are being included, if not - there should be messages explaining why not, like "not building UI because UI build mode is set to NEVER" or something alike

**Comment by weekends** [comment]
I'm make clean build and collect all logs. Attached...

[build.log](https://github.com/user-attachments/files/19503679/build.log)

**Comment by dyarkovoy** [comment]
What about the folder /home/grigory/workspace/esp32/Weekend/core/examples/basic/managed_components/esp32m/web-ui ? does it exist and accessible?

**Comment by weekends** [comment]
Yes.

grigory@weekend core/examples/basic $ ls -la /home/grigory/workspace/esp32/Weekend/core/examples/basic/managed_components/esp32m/web-ui
итого 528
drwxr-xr-x  5 grigory grigory   4096 мар 28 12:54 .
drwxr-xr-x  6 grigory grigory   4096 мар 28 12:54 ..
-rw-r--r--  1 grigory grigory   1942 мар 28 12:54 .eslintrc.json
drwxr-xr-x  3 grigory grigory   4096 мар 28 12:54 esp32m
-rw-r--r--  1 grigory grigory    828 мар 28 12:54 package.json
-rw-r--r--  1 grigory grigory    107 мар 28 12:54 .prettierrc.json
-rw-r--r--  1 grigory grigory    745 мар 28 12:54 tsconfig.base.json
-rw-r--r--  1 grigory grigory     78 мар 28 12:54 tsconfig.json
drwxr-xr-x 13 grigory grigory   4096 мар 28 12:54 ts-libs
drwxr-xr-x  4 grigory grigory   4096 мар 28 12:54 .yarn
-rw-r--r--  1 grigory grigory 491926 мар 28 12:54 yarn.lock
-rw-r--r--  1 grigory grigory    179 мар 28 12:54 .yarnrc.yml

**Comment by dyarkovoy** [comment]
Okay. So for whatever reason this command fails:
```
cd  /home/grigory/workspace/esp32/Weekend/core.test/examples/basic/build/web-ui
yarn link /home/grigory/workspace/esp32/Weekend/core.test/examples/basic/managed_components/esp32m/web-ui -A
```
See if you can run this command manually with `--verbose` flag to get more info

**Comment by weekends** [comment]
yarn can't recognise --verbose option :(

grigory@weekend core/examples/basic $ cd  /home/grigory/workspace/esp32/Weekend/core.test/examples/basic/build/web-ui
yarn link /home/grigory/workspace/esp32/Weekend/core.test/examples/basic/managed_components/esp32m/web-ui -A
➤ YN0000: · Yarn 4.1.0
➤ YN0000: ┌ Resolution step
➤ YN0001: │ RequestError
    at ClientRequest.<anonymous> (/home/grigory/workspace/esp32/Weekend/core.test/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:147:14258)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:530:35)
    at u.emit (/home/grigory/workspace/esp32/Weekend/core.test/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:142:14420)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)AggregateError [ETIMEDOUT]:
    at internalConnectMultiple (node:net:1139:18)
    at internalConnectMultiple (node:net:1215:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1739:5)
    at listOnTimeout (node:internal/timers:596:11)
    at process.processTimers (node:internal/timers:529:7)
➤ YN0000: └ Completed in 2m 32s
➤ YN0000: · Failed with errors in 2m 32s

**Comment by dyarkovoy** [comment]
right, it is removed in yarn 4 unfortunately.
Well, I'm out of ideas for the moment. 
Let me know what Linux flavor you are using, I will see if I can reproduce the problem on my end when I have time.
I do most of my development on Windows and may have missed some linux-specific issues.

**Comment by weekends** [comment]
I'm test on AltLinux sisyphus version, but this is not so popular variant. Also i'm try to compile on debian 12.10, issue same till remove yarn.lock, after i has troubles with compiling of other modules, like that:

ing.cpp.obj -c /home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/log/logging.cpp
 YN0000:  Completed in 0s 430ms
 YN0000:  Link step
 YN0072:  The application uses portals and that's why --preserve-symlinks Node option is required for launching it
 YN0000:  Completed in 0s 396ms
 YN0000:  Done with warnings in 1s 121ms
esp32m-ui:INFO:building /home/grigory/esp/esp32m-core/examples/basic/build/web-ui
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/log/logging.cpp: In function 'void esp32m::log::removeAppender(LogAppender*)':
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/log/logging.cpp:475:52: error: cannot convert 'std::vector<esp32m::log::LogAppender*>::iterator' to 'const char*'
  475 |       _appenders.erase(std::remove(_appenders.begin(), _appenders.end(), a),
      |                                    ~~~~~~~~~~~~~~~~^~
      |                                                    |
      |                                                    std::vector<esp32m::log::LogAppender*>::iterator
In file included from /home/grigory/esp/esp-idf/components/esp_hw_support/include/esp_intr_alloc.h:11,
                 from /home/grigory/esp/esp-idf/components/esp_hw_support/include/esp_cpu.h:20,
                 from /home/grigory/esp/esp-idf/components/esp_hw_support/include/spinlock.h:11,
                 from /home/grigory/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:49,
                 from /home/grigory/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include/freertos/portable.h:57,
                 from /home/grigory/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include/freertos/FreeRTOS.h:69,
                 from /home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/include/esp32m/logging.hpp:3,
                 from /home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/log/logging.cpp:1:
/home/grigory/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/xtensa-esp-elf/include/stdio.h:252:17: note:   initializing argument 1 of 'int remove(const char*)'
  252 | int     remove (const char *);
      |                 ^~~~~~~~~~~~
make[2]: *** [esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/build.make:188: esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/log/logging.cpp.obj] Ошибка 1

**Comment by dyarkovoy** [comment]
okay, I will try it on debian 12.10 and will let you know.

**Comment by dyarkovoy** [comment]
I installed Debian 12.10, fixed logging.cpp issue (indeed, there was a problem with #include ordering that manifested on Linux only) and I was able to compile. There was no yarn issue though. Anyhow, please update and see if you still have issues

**Comment by weekends** [comment]
Failure on debian with loggin, but no yarn problems:

[ 97%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/debug/diag.cpp.obj
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/io/gpio.cpp: In member function 'esp_err_t esp32m::gpio::PWM::ensureChannel()':
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/io/gpio.cpp:704:9: warning: missing initializer for member 'ledc_channel_config_t::sleep_mode' [-Wmissing-field-initializers]
  704 |         };
      |         ^
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/io/gpio.cpp: In member function 'virtual esp_err_t esp32m::gpio::LEDC::config(uint32_t, ledc_mode_t, ledc_timer_bit_t, ledc_clk_cfg_t)':
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/io/gpio.cpp:742:9: warning: missing initializer for member 'ledc_channel_config_t::sleep_mode' [-Wmissing-field-initializers]
  742 |         };
      |         ^
[ 97%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/debug/partitions.cpp.obj
[ 97%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/debug/pcf857x.cpp.obj
[ 97%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/debug/sysled.cpp.obj
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/log/logging.cpp: In function 'void esp32m::log::removeAppender(LogAppender*)':
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/log/logging.cpp:475:52: error: cannot convert 'std::vector<esp32m::log::LogAppender*>::iterator' to 'const char*'
  475 |       _appenders.erase(std::remove(_appenders.begin(), _appenders.end(), a),
      |                                    ~~~~~~~~~~~~~~~~^~
      |                                                    |
      |                                                    std::vector<esp32m::log::LogAppender*>::iterator
In file included from /home/grigory/esp/esp-idf/components/esp_hw_support/include/esp_intr_alloc.h:11,
                 from /home/grigory/esp/esp-idf/components/esp_hw_support/include/esp_cpu.h:20,
                 from /home/grigory/esp/esp-idf/components/esp_hw_support/include/spinlock.h:11,
                 from /home/grigory/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:49,
                 from /home/grigory/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include/freertos/portable.h:57,
                 from /home/grigory/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include/freertos/FreeRTOS.h:69,
                 from /home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/include/esp32m/logging.hpp:3,
                 from /home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/log/logging.cpp:1:
/home/grigory/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/xtensa-esp-elf/include/stdio.h:252:17: note:   initializing argument 1 of 'int remove(const char*)'
  252 | int     remove (const char *);
      |                 ^~~~~~~~~~~~
[ 97%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/debug/tasks.cpp.obj
[ 97%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/debug/lwip/mld6.cpp.obj
[ 98%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/debug/lwip/nd6.cpp.obj
[ 98%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/integrations/ha/ha.cpp.obj
[ 98%] Building CXX object esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/integrations/influx/mqtt.cpp.obj
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/net/wifi.cpp: In member function 'virtual void esp32m::net::Wifi::handleEvent(esp32m::Event&)':
/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/net/wifi.cpp:818:54: warning: 'int esp_rrm_send_neighbor_rep_request(neighbor_rep_request_cb, void*)' is deprecated: Use 'esp_rrm_send_neighbor_report_request' instead [-Wdeprecated-declarations]
  818 |             int e = esp_rrm_send_neighbor_rep_request(neighbor_report_recv_cb,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
  819 |                                                       this);
      |                                                       ~~~~~
In file included from /home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/net/wifi.cpp:17:
/home/grigory/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_rrm.h:42:5: note: declared here
   42 | int esp_rrm_send_neighbor_rep_request(neighbor_rep_request_cb cb,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/build.make:188: esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/src/log/logging.cpp.obj] Ошибка 1
make[2]: *** Ожидание завершения заданий…
make[1]: *** [CMakeFiles/Makefile2:6096: esp-idf/esp32m/CMakeFiles/__idf_esp32m.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…
 YN0085:  + @esp32m/ui@portal:/home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/web-ui/esp32m/ui::locator=ui%40workspace%3A., and 770 more.
 YN0000:  Completed in 5m 13s
 YN0000:  Fetch step
 YN0013:  9 packages were added to the project (+ 9.49 MiB).
 YN0000:  Completed in 18s 289ms
 YN0000:  Link step

**Comment by weekends** [comment]
On AltLinux i have same problems with yarn :(

[log.txt](https://github.com/user-attachments/files/19525276/log.txt)

**Comment by dyarkovoy** [comment]
check this file: /home/grigory/esp/esp32m-core/examples/basic/managed_components/esp32m/src/log/logging.cpp
does it have this line: https://github.com/esp32m/core/blob/de3fee4f4d71c4430f61c2b04ac0d22d553004f5/esp32m/src/log/logging.cpp#L16

**Comment by weekends** [comment]
No that line.

git pull and clean build, but no that include.

**Comment by weekends** [comment]
I'm make git clone again and try again. Now i see that change.

**Comment by dyarkovoy** [comment]
it's a good practice to use idf.py fullclean AND remove dependencies.lock file if you want clean rebuild

**Comment by weekends** [comment]
That's build results after git clone:

    at async Pt.resolveEverything (/home/grigory/esp/esp32m-core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:210:7138)
[ 98%] Built target esp32m_web_ui
[ 98%] Building ASM object esp-idf/web-ui/CMakeFiles/__idf_web-ui.dir/__/__/web-ui/dist/main.js.S.obj
[100%] Building ASM object esp-idf/web-ui/CMakeFiles/__idf_web-ui.dir/__/__/web-ui/dist/index.html.S.obj
[100%] Linking C static library libweb-ui.a
[100%] Built target __idf_web-ui
[100%] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj
/home/grigory/esp/esp32m-core/examples/basic/main/main.cpp:16:10: fatal error: dist/ui.hpp: No such file or directory
   16 | #include <dist/ui.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [esp-idf/main/CMakeFiles/__idf_main.dir/build.make:76: esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:6194: esp-idf/main/CMakeFiles/__idf_main.dir/all] Ошибка 2
make: *** [Makefile:136: all] Ошибка 2
BUG: component_requirements.py: cannot match original component filename for source component main
make failed with exit code 2, output of the command is in the /home/grigory/esp/esp32m-core/examples/basic/build/log/idf_py_stderr_output_1516511 and /home/grigory/esp/esp32m-core/examples/basic/build/log/idf_py_stdout_output_1516511

**Comment by dyarkovoy** [comment]
again this is about dist/ui.hpp which is a generated file, so do yo have the same yarn issue? look for 
```
YN0000: Yarn 4.1.0
YN0000: Resolution step
YN0001: RequestError
at ClientRequest. (/home/grigory/workspace/esp32/Weekend/core/examples/basic/build/web-ui/.yarn/releases/yarn-4.1.0.cjs:147:14258)
```
If you get this error, check your nodejs version (`nodejs --version`) and how you installed nodejs and yarn, maybe the problem is there. Here is how I did it and it worked for me:
```
curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh
sudo -E bash nodesource_setup.sh
sudo apt-get install -y nodejs
sudo npm install -g corepack
```

**Comment by weekends** [comment]
On debian, when i'm remove yarn.lock, now example compiled.
nodejs --version
v18.19.0

nodejs installed by apt-get install nodejs.
yarn installed like you propose.

**Comment by dyarkovoy** [comment]
okay then on altlinux you may want to check nodejs/yarn version, too.
I would use more recent nodejs version, like 22 or 23

**Comment by weekends** [comment]
On debian system also strange work:
1.Compile on clean build work only if i'm remove yarn.lock
2.After idf.py fullclean compiling not work with same err ui.hpp not available.

Also i see strange with managed_components/esp32m component's, this components build system take from network instead of local copy.

**Comment by dyarkovoy** [comment]
Item 1 - I can't confirm that, just tried clean build on debian a couple of times and it works fine. Here is the script I use:
```
#!/bin/sh
cd ~/esp32m
git clone https://github.com/esp32m/core.git
cd ~/esp-idf/
. ./export.sh
cd ~/esp32m/core/examples/basic
idf.py fullclean
idf.py build
```
Item 2 - yes, fullclean doesn't really clean things fully. For example, it doesn't remove dependencies.lock as it should (I think)

**Comment by weekends** [comment]
After idf.py fullclean i can't compile at all, dependencies.lock also removed.
idf.py fullclean
rm -f dependencies.lock
idf.py build

Compilation not complete. Also, esp32m not linked to managed_components, it all time downloaded from net. I'm make some changes in esp32m/src/net/ethernet.cpp after fullclean but no that changes inside managed_components

**Comment by dyarkovoy** [comment]
Regarding managed_components, this is how esp-idf works, it always updates managed_components and overwrites your local changes. If you want to make changes to esp32m code, make it under core/esp32m folder, and in your project change reference to your local copy of esp32m in main/idf_component.yml:
```
dependencies:
  idf: ">=5.1"
  esp32m:
    path: your-path/core/esp32m
```

Regarding problems with fullclean, here is the video showing how it succeeds for me on debian 12.10: 
https://youtu.be/Lbwg0h_RqzY 
I can record a video of installing debian 12.10 from scratch, installing the toolchain and then running the build with and without fullclean, let me know if you need it. I understand it doesn't fix your problem, but if I can do it successfully - maybe if you repeat my steps exactly as the video shows, it will work for you, too
